---
abstract: 'Run chmod recursively against directories'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-chmod-Recursive
provides:
  File::chmod::Recursive:
    file: lib/File/chmod/Recursive.pm
    version: 0.05
requires:
  File::chmod: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-chmod-Recursive
  homepage: https://github.com/mithun/perl-file-chmod-recursive
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-file-chmod-recursive.git
version: 0.05
